### ISSUE TITLE
I know this is good but don't know why!

### ISSUE THREAD

**Issue by nathanielks** [Hywan/gutenberg-parser-rs#10]
Please forgive my obtusity! I know this project is a good idea, but I'm not 100% sure why and was hoping you could shed a little light! Is the purpose of this project to offload parsing of Gutenberg-formatted WordPress posts off of WordPress/PHP but onto this extension so as to speed up page rendering? And because Rust can compile to multiple targets, makes it possible to parse Gutenberg-formatted posts in other environments than just PHP (ie a headless WordPress environment)? Thanks for your time and publishing your work?

**Comment by Hywan** [comment]
There is nothing to forgive :-).

This project is an experiment to, first, speed up the client-side with large posts (with the couple Rust + WASM). Then, because Rust can be embedded everywhere, the project continues to, second, speed up the server-side (with the triple Rust + C + PHP). Same for NodeJS, and maybe soon Java for Android, or Swift for iOS.

On client-side, rendering happens only on the editor. On the server-side, the parser is not used right now, since few regexes are able to handle special dynamic rendering. So on the server-side, the parser is used to analyse the structure of a post, or stuff like that, e.g. “headless WordPress” as you mentionned.

Did I answer your questions?

**Comment by nathanielks** [comment]
Aye, you sure did. Thanks @Hywan 😄
