### ISSUE TITLE
Still garbage data to remove

### ISSUE THREAD

**Issue by Hywan** [Hywan/gutenberg-parser-rs#4]
When running:

```sh
$ just build-wasm
$ twiggy garbage bindings/wasm/gutenberg_post_parser.wasm
 Bytes │ Size % │ Garbage Item
───────┼────────┼─────────────
  6285 ┊  6.78% ┊ data[6]
  1900 ┊  2.05% ┊ data[7]
  1850 ┊  2.00% ┊ data[2751]
  1796 ┊  1.94% ┊ data[2806]
  1737 ┊  1.87% ┊ data[2809]
  1486 ┊  1.60% ┊ data[2639]
  1478 ┊  1.60% ┊ data[2728]
  1454 ┊  1.57% ┊ data[2739]
  1445 ┊  1.56% ┊ data[2766]
  1302 ┊  1.41% ┊ data[2762]
```

we can see that there is still useless data.

`wasm-gc` and `wasm-opt` apparently failed to remove them; those commands are run by `just build-wasm`:

https://github.com/Hywan/gutenberg-parser-rs/blob/4a8db611ba8497441eb9130822381f2731e8015a/justfile#L33-L38

Any idea how to remove them? Is it true they are garbage? cc @fitzgen

**Comment by fitzgen** [comment]
Unfortunately, there isn't a good way to remove them right now. Most likely, these are data segments that were previously used by snipped functions (and/or possibly twiggy is failing to reconstruct some edges in the graph). `wasm-gc` won't collect unused data segments, because to do that soundly, you need the relocations info -- you can't precisely reconstruct the which-functions-use-which-data from just the code.

When rustc updates its llvm, we might be able to try something like:

* use a custom linker flag to tell `lld` to leave the relocations in the final `.wasm` artifact
* have `wasm-snip` understand and fix up the relocations when snipping functions
* re-run `lld` with the `--gc-sections` flag (better version of `wasm-gc` essentially) to remove now unused data segments and produce the actual final `.wasm` artifact

This will require some experimentation and work to make it relatively ergonomic :-p

**Comment by Hywan** [comment]
Fixed with recent `rustc` updates.
